import { StatusBadge } from '../components/StatusBadge';
import { Icon } from '../components/Icon';
import { PageHeader } from '../components/PageHeader';

const recommendations = [
  {
    id: 'AI-1247',
    title: 'Pricing Improvement Opportunity',
    description: 'Analysis shows 12 loans could achieve +8-15 bps better execution by switching to Investor B',
    impact: '+$18,400 estimated gain',
    confidence: 'High',
    loans: 12,
    action: 'Review Recommendations',
    basis: 'Based on historical bid patterns and current investor appetite for similar loan profiles'
  },
  {
    id: 'AI-1246',
    title: 'Near-Miss Eligibility Detection',
    description: '5 loans scored 0.5-2.0 points below investor guidelines. Minor adjustments could unlock eligibility',
    impact: '5 additional eligible loans',
    confidence: 'Medium',
    loans: 5,
    action: 'View Details',
    basis: 'Scoring model identified loans within 2 points of eligibility threshold across DTI and credit score dimensions'
  },
  {
    id: 'AI-1245',
    title: 'Lock Extension Risk Alert',
    description: '8 locks expiring in 5-7 days show elevated fallout risk based on borrower engagement patterns',
    impact: 'Potential $3.2M fallout',
    confidence: 'High',
    loans: 8,
    action: 'Contact Borrowers',
    basis: 'Engagement scoring model detected reduced communication frequency and delayed document submission'
  },
  {
    id: 'AI-1244',
    title: 'Margin Optimization',
    description: 'Conv 30Y product pricing could be adjusted +3-5 bps while maintaining 95%+ win rate',
    impact: '+$12,200/month revenue',
    confidence: 'Medium',
    loans: 247,
    action: 'Run Scenario',
    basis: 'Price elasticity model analyzed 90 days of competitive data and pull-through rates'
  },
];

export function AIInsights() {
  return (
    <div className="p-4">
      <PageHeader
        title="AI Insights"
        subtitle="Model version 2.4.1 | Last refresh: 2026-04-27 10:30 AM EDT"
        productColor="#9B51E0"
        showLogo={true}
      />

      <div
        className="bg-[#e7ecfc] border border-[#b8d0fe] p-4 mb-6 flex items-start gap-3"
        style={{ borderRadius: 'var(--radius-base)' }}
      >
        <Icon name="circle-info" size={16} className="text-[#1c67fe] mt-0.5 flex-shrink-0" />
        <div className="flex-1">
          <div className="text-xs mb-1 text-[#1e1e1e]">All recommendations generated by Polly AI include confidence scores and data traceability. Review before taking action.</div>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-2.5 mb-4">
        <div className="bg-card border border-border p-4"
          style={{ borderRadius: 'var(--radius-base)', boxShadow: 'var(--shadow-m)' }}>
          <div className="flex items-center gap-3 mb-2">
            <Icon name="circle-check" size={16} className="text-[#6fcf97]" />
            <div>
              <div className="text-xs text-muted-foreground uppercase tracking-wide">Actionable Insights</div>
              <div className="text-xl mt-0.5">4</div>
            </div>
          </div>
          <div className="text-xs text-muted-foreground">Last 24 hours</div>
        </div>

        <div className="bg-card border border-border p-4"
          style={{ borderRadius: 'var(--radius-base)', boxShadow: 'var(--shadow-m)' }}>
          <div className="flex items-center gap-3 mb-2">
            <Icon name="trending-up" size={16} className="text-[#1c67fe]" />
            <div>
              <div className="text-xs text-muted-foreground uppercase tracking-wide">Potential Gain</div>
              <div className="text-xl mt-0.5">$30.6K</div>
            </div>
          </div>
          <div className="text-xs text-muted-foreground">Active recommendations</div>
        </div>

        <div className="bg-card border border-border p-4"
          style={{ borderRadius: 'var(--radius-base)', boxShadow: 'var(--shadow-m)' }}>
          <div className="flex items-center gap-3 mb-2">
            <Icon name="sparkles" size={16} className="text-[#9b51e0]" />
            <div>
              <div className="text-xs text-muted-foreground uppercase tracking-wide">Avg Confidence</div>
              <div className="text-xl mt-0.5">94.2%</div>
            </div>
          </div>
          <div className="text-xs text-muted-foreground">All predictions</div>
        </div>
      </div>

      <div className="space-y-3">
        {recommendations.map((rec) => (
          <div key={rec.id} className="bg-card border border-border p-5"
            style={{ borderRadius: 'var(--radius-base)', boxShadow: 'var(--shadow-m)' }}>
            <div className="flex items-start gap-4 mb-2.5">
              <Icon name="sparkles" size={16} className="text-muted-foreground mt-0.5 flex-shrink-0" />
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <h3 className="text-sm">{rec.title}</h3>
                  <StatusBadge
                    status={rec.confidence === 'High' ? 'success' : 'warning'}
                    label={`${rec.confidence} Confidence`}
                  />
                  <span className="text-xs text-muted-foreground ml-auto">{rec.id}</span>
                </div>
                <div className="text-sm text-foreground mb-2.5">{rec.description}</div>

                <div className="grid grid-cols-2 gap-3 mb-2.5">
                  <div className="bg-muted/30 rounded-sm p-2.5">
                    <div className="text-xs text-muted-foreground mb-0.5 uppercase tracking-wide">Impact</div>
                    <div className="text-sm">{rec.impact}</div>
                  </div>
                  <div className="bg-muted/30 rounded-sm p-2.5">
                    <div className="text-xs text-muted-foreground mb-0.5 uppercase tracking-wide">Affected Loans</div>
                    <div className="text-sm">{rec.loans} loans</div>
                  </div>
                </div>

                <div className="bg-muted/20 border border-border rounded-sm p-3 mb-2.5">
                  <div className="flex items-start gap-2">
                    <Icon name="circle-exclamation" size={14} className="text-muted-foreground mt-0.5 flex-shrink-0" />
                    <div>
                      <div className="text-xs text-muted-foreground mb-1 uppercase tracking-wide">Basis</div>
                      <div className="text-xs text-muted-foreground">{rec.basis}</div>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <button className="px-3 py-1.5 bg-primary text-primary-foreground text-sm hover:bg-primary/90" style={{ borderRadius: 'var(--radius-xl)' }}>
                    {rec.action}
                  </button>
                  <button className="px-3 py-1.5 border border-border text-sm hover:bg-muted/30" style={{ borderRadius: 'var(--radius-xl)' }}>
                    View Traceability
                  </button>
                  <button className="text-xs text-muted-foreground hover:text-foreground ml-auto">Dismiss</button>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
