name: Publish Beta Version

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-library:
    name: Build and Publish Beta Library
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.version }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun run build:components
      - name: Publish Library
        id: publish
        run: bun publish-components-beta
