from __future__ import annotations

import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable

import fitz
import openpyxl
from docx import Document
from pptx import Presentation


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
GTM_DIR = DOCS / "GTM -20260413T175856Z-3-001" / "GTM"
ARCHIVE_DIR = DOCS / "(DNU) ARCHIVED sales collateral"
OUT = DOCS / "reference" / "company" / "collateral-extract-notes.md"


def _rel_repo(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def read_pdf_snippet(path: Path, max_chars: int = 1600) -> str:
    try:
        doc = fitz.open(path)
        text = "".join(page.get_text("text") for page in doc[:2]).strip()
        if not text:
            return "(No extractable text detected.)"
        return text[:max_chars].replace("\n", " ").strip()
    except Exception as exc:  # noqa: BLE001
        return f"(Error extracting PDF: {exc})"


def read_docx_snippet(path: Path, max_lines: int = 20) -> list[str]:
    try:
        doc = Document(path)
        lines = [p.text.strip() for p in doc.paragraphs if p.text.strip()]
        return lines[:max_lines] if lines else ["(No paragraph text detected.)"]
    except Exception as exc:  # noqa: BLE001
        return [f"(Error extracting DOCX: {exc})"]


def read_xlsx_snippet(path: Path, max_rows: int = 8) -> list[str]:
    try:
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        out: list[str] = [f"Sheets: {', '.join(wb.sheetnames)}"]
        for ws_name in wb.sheetnames[:3]:
            ws = wb[ws_name]
            out.append(f"Worksheet: {ws_name}")
            rows = ws.iter_rows(min_row=1, max_row=25, values_only=True)
            kept = 0
            for row in rows:
                if kept >= max_rows:
                    break
                values = [str(v).strip() for v in row if v is not None and str(v).strip()]
                if values:
                    out.append(" | ".join(values[:8]))
                    kept += 1
        return out
    except Exception as exc:  # noqa: BLE001
        return [f"(Error extracting XLSX: {exc})"]


def read_pptx_snippet_zip_xml(path: Path, max_slides: int = 8) -> list[str]:
    """Fallback when python-pptx fails on some decks (e.g. layout rId issues)."""
    try:
        with zipfile.ZipFile(path, "r") as zf:
            slide_names = sorted(
                n
                for n in zf.namelist()
                if n.startswith("ppt/slides/slide") and n.endswith(".xml")
            )
            out = [f"Slides: {len(slide_names)} (zip/XML fallback)"]
            for i, name in enumerate(slide_names[:max_slides], start=1):
                data = zf.read(name)
                root = ET.fromstring(data)
                texts: list[str] = []
                for elem in root.iter():
                    tag = elem.tag.split("}")[-1]
                    if tag == "t" and elem.text and elem.text.strip():
                        texts.append(elem.text.strip())
                sample = " || ".join(texts[:5]) if texts else "(No text found on slide)"
                out.append(f"Slide {i}: {sample[:260]}")
            return out
    except Exception as exc:  # noqa: BLE001
        return [f"(Error extracting PPTX via zip/XML: {exc})"]


def read_pptx_snippet(path: Path, max_slides: int = 8) -> list[str]:
    try:
        prs = Presentation(path)
        out = [f"Slides: {len(prs.slides)}"]
        for i, slide in enumerate(prs.slides[:max_slides], start=1):
            chunks: list[str] = []
            for shape in slide.shapes:
                if hasattr(shape, "text") and shape.text and shape.text.strip():
                    chunks.append(shape.text.strip().replace("\n", " "))
            sample = " || ".join(chunks[:3]) if chunks else "(No text found on slide)"
            out.append(f"Slide {i}: {sample[:260]}")
        return out
    except Exception:
        return read_pptx_snippet_zip_xml(path, max_slides=max_slides)


def list_files(base: Path, patterns: Iterable[str]) -> list[Path]:
    files: list[Path] = []
    for pattern in patterns:
        files.extend(base.rglob(pattern))
    return sorted({f for f in files if f.is_file()})


def section(title: str, lines: list[str]) -> str:
    body = "\n".join(f"- {line}" for line in lines)
    return f"## {title}\n\n{body}\n"


def main() -> None:
    lines: list[str] = [
        "# Collateral Extract Notes",
        "",
        "Generated by `scripts/extract_collateral_summary.py`.",
        "",
        f"- GTM root: `{_rel_repo(GTM_DIR)}`",
        f"- Archived root: `{_rel_repo(ARCHIVE_DIR)}`",
        "",
    ]

    gtm_xlsx = list_files(GTM_DIR, ["*.xlsx"])
    gtm_docx = list_files(GTM_DIR, ["*.docx"])
    gtm_pptx = list_files(GTM_DIR, ["*.pptx"])
    arch_pdf = list_files(ARCHIVE_DIR, ["*.pdf"])
    arch_docx = list_files(ARCHIVE_DIR, ["*.docx"])
    arch_xlsx = list_files(ARCHIVE_DIR, ["*.xlsx"])
    arch_pptx = list_files(ARCHIVE_DIR, ["*.pptx"])

    lines.extend(
        [
            "## Inventory",
            "",
            f"- GTM XLSX: {len(gtm_xlsx)}",
            f"- GTM DOCX: {len(gtm_docx)}",
            f"- GTM PPTX: {len(gtm_pptx)}",
            f"- Archived PDF: {len(arch_pdf)}",
            f"- Archived DOCX: {len(arch_docx)}",
            f"- Archived XLSX: {len(arch_xlsx)}",
            f"- Archived PPTX: {len(arch_pptx)}",
            "",
        ]
    )

    for path in gtm_xlsx:
        lines.append(section(f"GTM XLSX: {path.name}", read_xlsx_snippet(path)))
    for path in gtm_docx:
        lines.append(section(f"GTM DOCX: {path.name}", read_docx_snippet(path)))
    for path in gtm_pptx:
        lines.append(section(f"GTM PPTX: {path.name}", read_pptx_snippet(path)))

    for path in arch_docx[:5]:
        lines.append(section(f"Archived DOCX: {path.name}", read_docx_snippet(path)))
    for path in arch_xlsx[:3]:
        lines.append(section(f"Archived XLSX: {path.name}", read_xlsx_snippet(path)))
    for path in arch_pdf[:8]:
        lines.append(section(f"Archived PDF: {path.name}", [read_pdf_snippet(path)]))

    body = "\n".join(lines)
    body = "\n".join(line.rstrip() for line in body.splitlines()) + "\n"
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
